### ISSUE TITLE
Unable to get into Truck.

### ISSUE THREAD

**Issue by gabrielcalderon** [Boostvolt/tesla_semi#1]
The only way to get into the Truck is by spawning the Truck via code. When leaving the truck the ped gets stuck in the truck body. 

When you try to get into the truck again the ped just runs around the Truck.

**Comment by Boostvolt** [comment]
I personally have never had this before. Where exactly do you use the resource? Locally or on a server? Could you maybe send me a video?

**Comment by gabrielcalderon** [comment]
I'm using it in a hosted fivem server. I have no idea how to get a video. I will test it again tonight. 

FxServer artifacts: 2524
ESX 1.2

**Comment by Boostvolt** [comment]
Okay. Can you please join my discord server so I can better help you? Because the resources all work on my server. I hope I can better help you there and then fix the problem. It's a bit tricky on GitHub.
[discord.gg/KKnmPws](url)

**Comment by gabrielcalderon** [comment]
@Boostvolt After further testing, the issue went away. After pressing F, the ped will run for 3-4 seconds and then teleport inside the Semi.
